version: '3.7'
services:
  nextcloud:
    build:
      context: ./nextcloud
      dockerfile: Dockerfile
      args:
        GID: ${GID}
    ports:
      - 8787:80
    volumes:
      - nextcloud-data:/var/www/html
      - ./data:/var/www/html/data
      - ./config:/var/www/html/config
      - /srv/share:/mnt/share
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  db-data:
  nextcloud-data:
