version: '3.7'
services:
  nextcloud:
    build:
      context: ./nextcloud
      dockerfile: Dockerfile
      args:
        GID: ${GID}
    ports:
      - "${NEXTCLOUD_PORT}:80"
    volumes:
      - ./html:/var/www/html
      - /srv/share:/mnt/share
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  db_data:
